Algoritmo "exercício 7"

Var
peso, altura, imc : real

Inicio
escreva ("Seu peso: ")
leia (peso)
escreva ("Sua altura: ")
leia (altura)
imc <- peso / altura ^ 2
se imc < 18.5 entao
escreva ("Abaixo do peso")
senao
se imc < 25 entao
escreva ("Peso normal")
senao
se imc < 30 entao
escreva ("Sobre peso")
senao
se imc <35 entao
escreva ("peso obeso")
senao
se imc > 35 entao
escreva ("Peso obeso morbido)
fimse
fimse
fimse
fimse
fimse
Fimalgoritmo