Algoritmo "EXERCICIO 12"

Var
idade1, idade2  : inteiro
 nomea, nomeb : caractere
Inicio
escreva ("Qual nome da primeira pessoa? ")
leia (nomea)
escreva ("Qual a idade de ",nomea,"?")
leia (idade1)
escreva ("Qual nome da segunda pessoa? ")
leia (nomeb)
escreva ("Qual idade de ",nomeb,"?")
leia (idade2)
se idade1 > idade2 entao
escreva (nomea," é mais velho(a)")
senao
escreva (nomeb," é mais velho(a)")
fimse
Fimalgoritmo