Algoritmo "EXERCICIO 9"

Var
numero, raiz, potencia, quociente, resultadoq : real


Inicio
Escreva ("Qual número? ")
leia (numero)
raiz <- raizq(numero)
potencia <- numero ^ 4
quociente <- numero / 2
resultadoq <- quociente * numero

escreval ("A raiz quadrada desse número é: ", raiz:2:2)
escreval ("Número elevado a 4º potência é: ", potencia:2:2)
escreval ("O número recebido vezes o quociente do número dividido por 2 é: ", resultadoq:2:2)
Fimalgoritmo