Algoritmo "EXERCICIO 4"

Var
timea, timeb, vencedor, empate : caractere
gola, golb : inteiro


Inicio
escreva ("Qual nome do primeiro time? ")
leia (timea)
escreva ("Qual nome do segundo time? ")
leia (timeb)
escreva ("Quantos gols o ",timea," fez? ")
leia (gola)
escreva ("Quantos gols o ",timeb," fez? ")
leia (golb)
se gola > golb entao
escreval ("O ",timea," foi vencedor")
senao
se golb > gola entao
escreval ("O ",timeb," foi vencedor")
senao
se gola = golb entao
escreva ("A partida ficou empatada")
fimse
fimse
fimse
Fimalgoritmo